Upgrade to Qt 6
openstudiocoalition/OpenStudioApplication pull request #461
Opened 2021-10-31 02:53 UTC by macumber

Fixes #438

2021-11-03 23:09 UTC, jmarrec requested changes

2021-11-03 23:09 UTC, jmarrec commented on src/openstudio_app/CMakeLists.txt
> +    fixup_bundle(\"${APPS_EXPANDED}\" \"${QTPLUGINS}\" \"${DIRS}\")
This is what it used to be!

```suggestion
    fixup_bundle(\"\${APPS_EXPANDED}\" \"${QTPLUGINS}\" \"${DIRS}\")
```

2022-01-12 10:15 UTC, jmarrec requested changes

2022-01-12 10:15 UTC, jmarrec commented on .github/workflows/app_build.yml
> +  QT_VERSION: 6.2.1
- [ ] TODO

```suggestion
  QT_VERSION: 6.2.2
```

2022-03-14 12:28 UTC, macumber commented on FindOpenStudioSDK.cmake
> +    set(OPENSTUDIO_EXPECTED_HASH 77c2bf77f07dc2e2af7658df55940c49)
Thanks @jmarrec !

2022-03-14 12:29 UTC, macumber commented
@jmarrec I was hoping to get this in in the next week if things look good, is that ok with you?

2022-03-14 12:32 UTC, jmarrec commented
@macumber Sure. But do note that it means dropping 18.04 support, as Qt 6 doesn't support it.

2022-03-20 03:47 UTC, macumber commented
@jmarrec I am good to merge this now.  Do you want to do any final review or testing on Ubuntu 20.04?

2022-04-08 09:22 UTC, jmarrec approved these changes
Assuming CI comes clean, we'll merge this one. We can bump to Qt 6.3.0 when it comes out.

2022-04-08 09:22 UTC, jmarrec commented on .github/workflows/app_build.yml
> +  QT_VERSION: 6.2.3
Qt 6.3.0 is planned in 4 days (original: 16.03.2022 , updated: 12.04.2022)

2022-04-08 10:37 UTC, merged